export const wordList = [
    { word: "سیب", hint: "پھل" },
    { word: "کیلا", hint: "پھل" },
    { word: "نارنجی", hint: "پھل" },
    { word: "انگور", hint: "پھل" },
    { word: "لیموں", hint: "پھل" },
    { word: "تربوز", hint: "پھل" },
    { word: "اناناس", hint: "پھل" },
    { word: "خوبانی", hint: "پھل" },
    { word: "خربوزہ", hint: "پھل" },
    { word: "انجیر", hint: "پھل" },

    { word: "شیر", hint: "جانور" },
    { word: "بلی", hint: "جانور" },
    { word: "خرگوش", hint: "جانور" },
    { word: "طوطا", hint: "جانور" },
    { word: "مور", hint: "جانور" },
    { word: "بکری", hint: "جانور" },
    { word: "گائے", hint: "جانور" },
    { word: "گھوڑا", hint: "جانور" },
    { word: "بطخ", hint: "جانور" },
    { word: "چیتا", hint: "جانور" },
    { word: "ہرن", hint: "جانور" },
    { word: "ہاتھی", hint: "جانور" },
    { word: "بندر", hint: "جانور" },


    { word: "گاجر", hint: "سبزی" },
    { word: "پیاز", hint: "سبزی" },
    { word: "ٹماٹر", hint: "سبزی" },
    { word: "بھنڈی", hint: "سبزی" },
    { word: "مولی", hint: "سبزی" },
    { word: "پالک", hint: "سبزی" },
    { word: "گوبھی", hint: "سبزی" },
    { word: "بینگن", hint: "سبزی" },
    

    { word: "کرکٹ", hint: "کھیل" },
    { word: "ہاکی", hint: "کھیل" },
    { word: "فٹبال", hint: "کھیل" },
    { word: "بیڈمنٹن", hint: "کھیل" },
    { word: "گالف", hint: "کھیل" },
    { word: "سکواش", hint: "کھیل" },

    { word: "ہانڈی", hint: "خوراک" },
    { word: "نہاری", hint: "خوراک" },
    { word: "حلیم", hint: "خوراک" },
    { word: "روٹی", hint: "خوراک" },
    { word: "کوفتے", hint: "خوراک" },
    { word: "بریانی", hint: "خوراک" },
    { word: "سموسہ", hint: "خوراک" },
    { word: "پکوڑا", hint: "خوراک" },
    { word: "کباب", hint: "خوراک" },
    { word: "کھیر", hint: "خوراک" },
    { word: "فالودہ", hint: "خوراک" },
    { word: "چاٹ", hint: "خوراک" },
    { word: "کھچڑی", hint: "خوراک" }
];
